version: '3.9'

services:
  imbrett-ui:
    container_name: imbrett-ui
    build:
      context: ./
      target: setup-stage
    ports:
      - '8080:8080'
    volumes:
      - './:/app'
    command: "yarn dev"
