name: "CodeQL"

on:
  workflow_run:
    workflows: ["Lint"]
    branches: [main, develop]
    types:
      - completed
  # Run every day at midnight
  schedule:
    - cron: '0 0 * * *'

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/analyze@v1
